#!/usr/bin/env bash
# Regenerate app/openapi.json from the live FastAPI app, then render it
# (widdershins) straight into vettd-e2e/docs/specs/query-service-api.md —
# the cross-repo contract doc lives there, not in this repo, since vettd
# and vettd-cli are the ones who have to agree with it. See
# vettd-e2e/docs/conventions/doc-placement.md.
#
# Idempotent — run it after any query_service.py request/response change,
# commit app/openapi.json here, and commit the rendered .md in vettd-e2e.
# CI should fail if `git diff --exit-code` is dirty in either repo afterward.
#
# See vettd-e2e/docs/recipes/keep-api-docs-in-sync.md for the cross-repo
# contract-sync process.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
SPEC="$ROOT/app/openapi.json"
SIBLING="$ROOT/../../vettd-e2e"
OUT="$SIBLING/docs/specs/query-service-api.md"

if [ ! -d "$SIBLING" ]; then
  echo "vettd-e2e sibling checkout not found at $SIBLING — clone it alongside" \
       "ah-skills, vettd, and vettd-cli (see vettd-e2e/docs/system/repos.md)." >&2
  exit 1
fi

echo "==> regenerating $SPEC from the live FastAPI app"
( cd app && uv run python -c "
import json, query_service
json.dump(query_service.app.openapi(), open('openapi.json', 'w'), indent=2)
open('openapi.json', 'a').write('\n')
" )

echo "==> rendering $OUT (widdershins)"
TMP="$(mktemp)"
npx -y widdershins@4.0.1 "$SPEC" -o "$TMP" \
  --language_tabs 'shell:curl' 'python:requests' \
  --summary --omitHeader

{
  echo "---"
  echo "title: Query service API (generated)"
  echo "description: Widdershins-rendered Markdown of ah-skills/search-demo's app/openapi.json — the FastAPI query-service's HTTP contract (/query, /scan, /scan/skill, /health). The authoritative HTTP surface both vettd and vettd-cli mirror."
  echo "topic: specs"
  echo "status: current"
  echo "last_verified: $(date +%Y-%m-%d)"
  echo "owner_repo: ah-skills/search-demo"
  echo "tags: [specs, openapi, query-service, generated]"
  echo "generated_by: cd ah-skills/search-demo && ./scripts/render_openapi_md.sh (writes here directly)"
  echo "---"
  echo
  echo "> **Cross-system spec** — generated here from \`ah-skills/search-demo/app/openapi.json\`" \
       "because it's a contract other repos read. Operational docs that stay in" \
       "\`ah-skills/search-demo\`: \`docs/DAILY_JOB.md\`. Placement rule:" \
       "[doc-placement.md](../conventions/doc-placement.md)."
  echo
  echo "<!-- GENERATED by ah-skills/search-demo/scripts/render_openapi_md.sh from app/openapi.json — DO NOT EDIT. -->"
  echo "<!-- Regenerate after any query_service.py request/response change; commit app/openapi.json there and this file here. -->"
  echo "<!-- Contract-sync process: vettd-e2e/docs/recipes/keep-api-docs-in-sync.md -->"
  echo
  # drop widdershins' Slate-viewer boilerplate line
  grep -v '^> Scroll down for code samples' "$TMP"
} > "$OUT"
rm -f "$TMP"

echo "==> done. Review: git diff app/openapi.json  (here)  and  git -C $SIBLING diff docs/specs/query-service-api.md"
