#!/usr/bin/env bash
# Regenerate app/openapi.json from the live FastAPI app, then render it to
# docs/QUERY_SERVICE_API.md (widdershins) for human review of spec diffs in PRs.
#
# Idempotent — run it after any query_service.py request/response change and
# commit both files. CI should fail if `git diff --exit-code` is dirty afterward.
#
# See vettd-e2e/KEEPING_API_DOCS_IN_SYNC.md for the cross-repo contract-sync process.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
SPEC="$ROOT/app/openapi.json"
OUT="$ROOT/docs/QUERY_SERVICE_API.md"

echo "==> regenerating $SPEC from the live FastAPI app"
( cd app && uv run python -c "
import json, query_service
json.dump(query_service.app.openapi(), open('openapi.json', 'w'), indent=2)
open('openapi.json', 'a').write('\n')
" )

echo "==> rendering $OUT (widdershins)"
TMP="$(mktemp)"
npx -y widdershins@4.0.1 "$SPEC" -o "$TMP" \
  --language_tabs 'shell:curl' 'python:requests' \
  --summary --omitHeader

{
  echo "<!-- GENERATED by scripts/render_openapi_md.sh from app/openapi.json — DO NOT EDIT. -->"
  echo "<!-- Regenerate after any query_service.py request/response change; commit both files. -->"
  echo "<!-- Contract-sync process: vettd-e2e/KEEPING_API_DOCS_IN_SYNC.md -->"
  echo
  # drop widdershins' Slate-viewer boilerplate line
  grep -v '^> Scroll down for code samples' "$TMP"
} > "$OUT"
rm -f "$TMP"

echo "==> done. Review: git diff app/openapi.json docs/QUERY_SERVICE_API.md"
